config/routes.rb
Rails.application.routes.draw do

  match 'users/password'      => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/new'  => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/edit' => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/sign_up'       => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]

  get 'overview' => 'overview#index'
  get 'overview/index'

  devise_for :users
  namespace :admin do
  resources :apikey
  end

  namespace :api do
  get 'game_result/new'
  get 'game_result/history'
  get 'game_result/statistic/:id' => 'game_result#statistic'
  get 'student/all'
  get 'student/one'
  end

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'

  resources :game_results

  resources :students

  root to:redirect('dashboard')

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :game_results, foreign_key: :student_id

  enum gender: [:M, :F]

  validates :name, :presence => true
  validates :gender, :presence => true, :inclusion => {in:['M', 'F']}
end

app/controllers/api/student_controller.rb
class Api::StudentController < ApplicationController
  before_action :api_auth

  def all
    @students = Student.all
    respond_to do |format|
      format.xml { render :xml => @students.to_xml(:only => [:id, :name, :gender]) }
      format.json { render :json => @students.to_json(:only => [:id, :name, :gender]) }
      # format.json do
      #   render :json => @students.to_json
      # end
    end
  end

  def one
    @student = []
    begin
      @student = Student.find(params['id'].to_i)
    rescue

    end
    respond_to do |format|
      format.xml { render :xml => @student.to_xml(:only => [:id, :name, :gender, :remarks]) }
      format.json { render :json => @student.to_json(:only => [:id, :name, :gender, :remarks]) }
    end
  end

  private

  def api_auth
    if params.has_key?(:token)
      #auth by apikey
      apikey = Apikey.find_by_key(params[:token])

      if apikey.nil?
        #key not found
        render json:{status:401, statusText:'unauthorized'}, :status => :unauthorized
        return false
      elsif apikey.secret == Digest::SHA2.new(512).hexdigest(params[:secret])
        #key match secret
        return true
      else
        #key not match secret
        render json:{status:401, statusText:'unauthorized'}, :status => :unauthorized
        return false
      end
    else
      #auth by login
      if signed_in?
        return true
      else
        render json:{status:401, statusText:'unauthorized'}, :status => :unauthorized
        return false
      end
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :select_student, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper
  def index
  end

  def new
    @student = Student.new
  end

  def create
    form_data = strong_params params
    form_data[:gender] = form_data[:gender].to_i
    @student = Student.new form_data
    @student.id = Student.maximum(:id) + 1 # for postgresql
    if @student.save
      flash[:notice] = "Student added: #{@student.name}"
      redirect_to new_student_path
    else
      flash[:error] = 'Add student failed, read errors below.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    form_data = strong_params(params)
    old_name = @student.name
    if @student.update(form_data)
      flash[:success] = "Student \"#{@student.name}\" updated"
      redirect_to student_path(@student)
    else
      if form_data['name'] == ''
        @student.name = old_name
      end
      flash[:error] = 'Student update failed, read errors below.'
      render :edit
    end
  end

  def destroy
    if @student.destroy
      flash[:success] = "Student \"#{@student.name}\" deleted."
      redirect_to students_path
    else
      flash[:error] = 'Delete failed. May be some records are using it.'
      redirect_to student_path(@student)
    end
  end

  def select_student
    @student
    begin
      @student = Student.find(params[:id].to_i)
    rescue

    end
  end

  def strong_params(params)
    params.require(:student).permit(:name, :gender, :remarks)
  end

end

app/helpers/api/student_helper.rb
module Api::StudentHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_studentForm.html.erb
<div class="form-group">
  <%= f.label :name, 'Student Name:', :class => 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :name, :class => 'form-control', :placeholder => 'Steve Jobs' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :gender, 'Gender:', :class => 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.select :gender, options_for_select(Student.genders), {}, :class => 'form-control' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :remarks, 'Remarks:', :class => 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_area :remarks, rows:5, :class => 'form-control', :placeholder => 'remarks...' %>
  </div>
</div>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      <%= @student.name if !@student.nil? %>
      <small></small>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <% if @student == nil %>
        <h2 class="text-center text-muted">No such student.</h2>
    <% else %>
        <% @student.errors.full_messages.each do |msg| %>
            <%= content_tag(:div,
                            content_tag(:button,
                                        content_tag(:span, '&times;'.html_safe ,aria:{hidden:'true'}) ,type:"button", class:"close", data:{dismiss:"alert"}) +
                                    msg, class:'alert alert-danger alert-dismissible', role:'alert')
            %>
        <% end %>
        <%= form_for @student, :url => student_path(@student), :method=>:patch, :html=>{:class => 'form-horizontal'} do |f| %>

            <%= render :partial => 'studentForm', :locals => {:f => f} %>

            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <%= f.submit 'Update', :class => 'btn btn-primary' %>
                <%= link_to 'Cancel', _back_url, class:'btn btn-default' %>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      <span class="glyphicon glyphicon-user"></span> Students
      <div class="pull-right">
        <%= link_to content_tag(:span,'',class:'glyphicon glyphicon-plus')+' Add', new_student_path, class:'btn btn-primary' %>
      </div>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <table id="table-of-students" class="table table-hover display responsive no-wrap"></table>
  </div>
</div>
<% load_js 'students_index.js' %>

app/views/students/new.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      Add Student
      <small>
        <%= "#{flash[:alert]} #{flash[:notice]}" %>
      </small>
    </h2>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <% if @student.errors.any? %>
        <% @student.errors.full_messages.each do |msg| %>
            <%= content_tag(:div,
                            content_tag(:button,
                                        content_tag(:span, '&times;'.html_safe ,aria:{hidden:'true'}) ,type:"button", class:"close", data:{dismiss:"alert"}) +
                                    msg, class:'alert alert-danger alert-dismissible', role:'alert')
            %>
        <% end %>
    <% end %>
    <%= form_for @student, :url => students_path , :html=>{:class => 'form-horizontal'} do |f| %>

        <%= render :partial => 'studentForm', :locals => {:f => f} %>



        <div class="form-group">
          <div class="col-sm-10 col-sm-offset-2">
            <%= f.submit 'Create', :class => 'btn btn-primary' %>
            <%= link_to 'Cancel', _back_url, class:'btn btn-default' %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      <% if !@student.nil? %>
          <%= @student.name %>

          <div class="pull-right">
            <div class="btn-group">
              <%= link_to content_tag(:span,'',class:'glyphicon glyphicon-wrench') + ' Edit', edit_student_path(@student), class:'btn btn-warning' %>
              <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="caret"></span>
                <span class="sr-only">Toggle Dropdown</span>
              </button>
              <ul class="dropdown-menu dropdown-menu-right">
                <li><%= link_to 'Delete', student_path(@student), :method => :delete, :data => { :confirm => "Delete #{@student.name}?" }  %></li>
              </ul>
            </div>
          </div>
      <% end %>

    </h2>
  </div>
</div>

<div class="col-sm-10 col-sm-offset-1">
  <div class="row">
    <% if @student.nil? %>
        <h2 class="text-center text-muted">No such student.</h2>
    <% else %>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title text-center"><%= @student.name %></h3>
          </div>
          <div class="panel-body">
            <table class="table table-hover table-striped">
              <tbody>
              <% @student.attributes.except('id', 'created_at','updated_at').each do |k, v| %>
                  <tr>
                    <th scope="row"><%= k.humanize %></th>
                    <td><%= k=='gender'? (v==0? 'M' : 'F') : v %></td>
                  </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>


        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title text-center">Game Records</h3>
          </div>
          <div class="panel-body">
            <div id="student-show-game-duration"></div>
          </div>
        </div>

    <% end %>

  </div>
</div>
<script type="text/javascript">
  //for google chart part
  var student_info = <%= @student.nil? ? -1 : @student.to_json.html_safe %>;
</script>

<%= load_js 'student_show.js' %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>