config/routes.rb
Rails.application.routes.draw do

  match 'users/password'      => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/new'  => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/edit' => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/sign_up'       => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]

  get 'overview' => 'overview#index'
  get 'overview/index'

  devise_for :users
  namespace :admin do
  resources :apikey
  end

  namespace :api do
  get 'game_result/new'
  get 'game_result/history'
  get 'game_result/statistic/:id' => 'game_result#statistic'
  get 'student/all'
  get 'student/one'
  end

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'

  resources :game_results

  resources :students

  root to:redirect('dashboard')

end

app/models/apikey.rb
class Apikey < ActiveRecord::Base

  validates :key, :presence => true
  validates :secret, :presence => true
end

app/controllers/admin/apikey_controller.rb
class Admin::ApikeyController < ApplicationController
  before_action :authenticate_user!
  before_action :select_apkey, :only => [:edit, :update, :destroy]

  def index
    @apikeys = Apikey.all.order(:created_at => :asc)
    gon.apikeys = @apikeys.each{|k| k.secret = ''; k}
    # if !@newApiKey.nil?
      gon.newApiKey = @newApiKey
    # end
  end

  def create
    #SecureRandom.base64(32)
    apikey = Apikey.new
    apikey.key = (0..16).map { ('a'..'z').to_a[rand(26)] }.join
    secret = SecureRandom.base64(32)
    apikey.secret = Digest::SHA2.new(512).hexdigest(secret)
    begin
      apikey.save!
      flash[:success] = 'API Key generated!'
      flash[:new_token] = apikey.key
      flash[:new_secret] = secret
    rescue
      flash[:error] = 'Generate API key failed!'
    end

    redirect_to admin_apikey_index_path
  end

  def edit
  end

  def update
    @apikey.remarks = params.require(:apikey).permit(:remarks)[:remarks]
    begin
      @apikey.save!
      flash[:success] = 'Remarks saved!'
    rescue
      flash[:error] = 'Save failed!'
    end
    redirect_to admin_apikey_index_path
  end

  def destroy
    begin
      @apikey.destroy!
      flash[:success] = 'API Key deleted!'
    rescue
      flash[:error] = 'Delete failed!'
    end
    redirect_to :back
  end

  def select_apkey
    @apikey = Apikey.find(params.permit(:id)[:id].to_i)
  end
end

app/helpers/admin/apikey_helper.rb
module Admin::ApikeyHelper
end

app/views/admin/apikey/create.html.erb
<h1>Admin::Apikey#create</h1>
<p>Find me in app/views/admin/apikey/create.html.erb</p>

app/views/admin/apikey/destroy.html.erb
<h1>Admin::Apikey#destroy</h1>
<p>Find me in app/views/admin/apikey/destroy.html.erb</p>

app/views/admin/apikey/edit.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      Edit "<%= @apikey.key if !@apikey.nil? %>"
      <small></small>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <% if @apikey == nil %>
        <h2 class="text-center text-muted">No such API key.</h2>
    <% else %>
        <% @apikey.errors.full_messages.each do |msg| %>
            <%= content_tag(:div,
                            content_tag(:button,
                                        content_tag(:span, '&times;'.html_safe ,aria:{hidden:'true'}) ,type:"button", class:"close", data:{dismiss:"alert"}) +
                                    msg, class:'alert alert-danger alert-dismissible', role:'alert')
            %>
        <% end %>
        <%= form_for @apikey, :url => admin_apikey_path(@apikey), :method=>:patch, :html=>{:class => 'form-horizontal'} do |f| %>

            <div class="form-group">
              <%= f.label :key, 'Key:', :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.text_field :key, :class => 'form-control',:readonly => true %>
              </div>
            </div>

            <div class="form-group">
              <%= f.label :remarks, 'Remarks:', :class => 'col-sm-2 control-label' %>
              <div class="col-sm-10">
                <%= f.text_area :remarks, rows:5,:placeholder => 'DO NOT put you secret key here!', :class => 'form-control' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-10 col-sm-offset-2">
                <%= f.submit 'Update', :class => 'btn btn-primary' %>
                <%= link_to 'Cancel', _back_url, class:'btn btn-default' %>
              </div>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/admin/apikey/index.html.erb
<div class="row">
  <div class="col-md-12 page-header">
    <h2>
      <span class="glyphicon glyphicon-link"></span> API Keys
      <div class="pull-right">
        <%= link_to content_tag(:span,'',class:'glyphicon glyphicon-plus')+' Create new', admin_apikey_index_path, class:'btn btn-primary', method:'POST' %>
      </div>
    </h2>
  </div>
</div>
<div class="row" id="apikey-show-container">
  <% if @apikeys.length == 0 %>
      <div class="col-md-12 text-center text-primary">No API Key. Click "Create new" to add one.</div>
  <% end %>

  <% if !flash[:new_token].nil? %>
    <div class="col-md-12">
      <%= content_tag(:div,simple_format("The secret key only show <strong>once</strong>, please save it to a secure place:<br /><strong>Access Token:</strong> <code id='new-token'>#{flash[:new_token]}</code><br /><strong>Secret Key</strong>: <code id='new-secret'>#{flash[:new_secret]}</code>"), class:'alert alert-info', role:'alert')  %>
    </div>
  <% end %>
</div>
<%= Gon::Base.render_data %>
<%= load_js 'admin/apikey_index.js' %>