config/routes.rb
Rails.application.routes.draw do

  match 'users/password'      => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/new'  => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/password/edit' => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/sign_up'       => redirect('/'), via: [:get, :post, :delete, :patch, :put]
  match 'users/cancel'        => redirect('/'), via: [:get, :post, :delete, :patch, :put]

  get 'overview' => 'overview#index'
  get 'overview/index'

  devise_for :users
  namespace :admin do
  resources :apikey
  end

  namespace :api do
  get 'game_result/new'
  get 'game_result/history'
  get 'game_result/statistic/:id' => 'game_result#statistic'
  get 'student/all'
  get 'student/one'
  end

  get 'dashboard' => 'dashboard#index'
  get 'dashboard/index'

  resources :game_results

  resources :students

  root to:redirect('dashboard')

end

app/models/apikey.rb
class Apikey < ActiveRecord::Base

  validates :key, :presence => true
  validates :secret, :presence => true
end

app/models/game_result.rb
class GameResult < ActiveRecord::Base
  belongs_to :student

  # validates :score, :presence => true,numericality:{greater_than_or_equal_to: 0}
  validates :duration, :presence => true,numericality:{greater_than_or_equal_to: 0}
  validates :object_total, :presence => true,numericality:{greater_than_or_equal_to: 0}
  validates :object_caught, :presence => true,numericality:{greater_than_or_equal_to: 0}
  validates :scene_id, :presence => true,numericality:{greater_than_or_equal_to: 1}
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :game_results, foreign_key: :student_id

  enum gender: [:M, :F]

  validates :name, :presence => true
  validates :gender, :presence => true, :inclusion => {in:['M', 'F']}
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username,
            :presence => true,
            :uniqueness => {
                :case_sensitive => false
            }

  # Only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username
  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      if conditions[:username].nil?
        where(conditions).first
      else
        where(username: conditions[:username]).first
      end
    end
  end
end

app/controllers/api/admin_controller.rb
class Api::AdminController < ApplicationController
  def dbsetup
    # @output = `rake db:setup`
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end

  # def configure_permitted_parameters
  #   added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
  #   devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  #   devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  # end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/game_results_controller.rb
class GameResultsController < ApplicationController

  before_action :authenticate_user!

  def index
  end

  def new
  end

  def create
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!
  before_action :select_student, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper
  def index
  end

  def new
    @student = Student.new
  end

  def create
    form_data = strong_params params
    form_data[:gender] = form_data[:gender].to_i
    @student = Student.new form_data
    @student.id = Student.maximum(:id) + 1 # for postgresql
    if @student.save
      flash[:notice] = "Student added: #{@student.name}"
      redirect_to new_student_path
    else
      flash[:error] = 'Add student failed, read errors below.'
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    form_data = strong_params(params)
    old_name = @student.name
    if @student.update(form_data)
      flash[:success] = "Student \"#{@student.name}\" updated"
      redirect_to student_path(@student)
    else
      if form_data['name'] == ''
        @student.name = old_name
      end
      flash[:error] = 'Student update failed, read errors below.'
      render :edit
    end
  end

  def destroy
    if @student.destroy
      flash[:success] = "Student \"#{@student.name}\" deleted."
      redirect_to students_path
    else
      flash[:error] = 'Delete failed. May be some records are using it.'
      redirect_to student_path(@student)
    end
  end

  def select_student
    @student
    begin
      @student = Student.find(params[:id].to_i)
    rescue

    end
  end

  def strong_params(params)
    params.require(:student).permit(:name, :gender, :remarks)
  end

end

app/helpers/admin/apikey_helper.rb
module Admin::ApikeyHelper
end

app/helpers/api/admin_helper.rb
module Api::AdminHelper
end

app/helpers/api/game_result_helper.rb
module Api::GameResultHelper
end

app/helpers/api/student_helper.rb
module Api::StudentHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bs_nav_active_class(link_path)
    current_page?(link_path) ? 'active' : ""
  end

  def load_js(*files)
    content_for(:head) { javascript_include_tag(*files) }
  end

  def convert_gender(student_form)
    case student_form[:gender]
      when '0'
        student_form[:gender] = 'M'
      when '1'
        student_form[:gender] = 'F'
    end
    student_form
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h3><strong>Oops! </strong>#{sentence}</h3>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/game_results_helper.rb
module GameResultsHelper
end

app/helpers/overview_helper.rb
module OverviewHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/_alerts.erb
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        flash[:success], class: 'alert alert-success alert-dismissible', role: 'alert') if flash[:success] != nil
%>
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        flash[:info], class: 'alert alert-info alert-dismissible', role: 'alert') if flash[:info] != nil
%>
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        flash[:warn], class: 'alert alert-warning alert-dismissible', role: 'alert') if flash[:warn] != nil
%>
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        flash[:error], class: 'alert alert-danger alert-dismissible', role: 'alert') if flash[:error] != nil
%>

<%# devise %>
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        notice, class: 'alert alert-success alert-dismissible', role: 'alert') if notice != nil
%>
<%= content_tag(:div,
                content_tag(:button,
                            content_tag(:span, '&times;'.html_safe, aria: {hidden: 'true'}), type: "button", class: "close", data: {dismiss: "alert"}) +
                        alert, class: 'alert alert-danger alert-dismissible', role: 'alert') if alert != nil
%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SunnyWalk</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script async type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <%= Gon::Base.render_data %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if signed_in? %>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-cloud" style="position: relative;top: 4px;"> </span> Sunny Walk</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Signed in as #{current_user.username}" %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Edit My Account', edit_user_registration_path %></li>
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li id="nav-dashboard"><%= link_to 'Dashboard', dashboard_index_path %></li>
          <li id="nav-apikey"><%= link_to 'API Key', admin_apikey_index_path %></li>
          <li id="nav-overview"><%= link_to 'Overview', overview_index_path %></li>
          <!--<li id="nav-reports"><a href="#">Reports (coming feature)</a></li>-->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li id="nav-students"><%= link_to 'Students', students_path %></li>
          <li id="nav-game-records"><%= link_to 'Game Records', game_results_path %></li>
        </ul>

      </div>
    </div>
  </nav>
<% end %>

<div class="container-fluid">
  <div class="row">
    <% if signed_in? %>
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="<%= bs_nav_active_class(dashboard_index_path)    %>"><%= link_to 'Dashboard', dashboard_index_path %></li>
            <%= content_tag(:li, link_to('API Key', admin_apikey_index_path), :class => bs_nav_active_class(admin_apikey_index_path)) %>
            <%= content_tag(:li, link_to('Overview', overview_path), :class => bs_nav_active_class(overview_path)) %>
            <!--<li><a href="#">Reports (coming feature)</a></li>-->
          </ul>
          <ul class="nav nav-sidebar">
            <li class="<%= bs_nav_active_class(students_path) %>" ><%= link_to 'Students', students_path %></li>
            <li class="<%= bs_nav_active_class(game_results_path) %>" ><%= link_to 'Game Records', game_results_path %></li>
          </ul>

        </div>

        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <%= render :partial => 'layouts/alerts' %>
          <%= yield %>
        </div>
    <% else %>
        <div class="col-md-10 col-md-offset-1 main">
          <%= render :partial => 'layouts/alerts' %>
          <%= yield %>
        </div>
    <% end %>
  </div>
</div>

<%= yield(:head) %>
</body>
</html>